name: BABY_1l_LiPb
channels:
  - conda-forge
dependencies:
  - python
  - openmc~=0.15.0
  - openmc-plotter
  - numpy # add version tag
  - scipy # add version tag
  - matplotlib # add version tag
  - sympy
  - pandas
  - pint-pandas
  - nbconvert
  - ipykernel
  - pint
  - pip
  - pip:
      - git+https://github.com/libra-project/libra-toolbox@v0.6.1
      - openmc_data_downloader~=0.6.0
      - matplotlib-label-lines
      - h-transport-materials~=0.17
